blank_issues_enabled: false

issue_template:
  - name: ğŸ Bug åé¦ˆ
    description: æäº¤ç½‘ç«™æˆ–åŠŸèƒ½ä½¿ç”¨ä¸­çš„é—®é¢˜
    file: bug_report.md
  - name: ğŸ’¡ åŠŸèƒ½å»ºè®®
    description: æå‡ºä¸€ä¸ªæ–°åŠŸèƒ½æˆ–æ”¹è¿›æƒ³æ³•
    file: feature_request.md
  - name: ğŸ§° è‡ªå®šä¹‰åé¦ˆ
    description: å…¶ä»–ç±»å‹çš„åé¦ˆæˆ–æ²Ÿé€š
    file: custom.md
